spring:
  application:
    name: FileUpload

  datasource:
    url: jdbc:mysql://localhost/fileuplaod
    username: root
    password: root123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true

  cloud:
    config:
      fail-fast: true
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
        retry:
          max-attempts: 6
          multiplier: 1.1
          initial-interval: 1000
          max-interval: 1000

# logging:
#   level:
#     org:
#       springframework:
#         web: debug

# PostGreSql
# spring:
#   datasource:
#     postgredb:
#       jdbc-url: jdbc:postgresql://localhost/fileupload
#       username: postgres
#       password: root123
#   jpa:
#     hibernate:
#       postgredb:
#         ddl-auto: update

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7070/eureka

polar:
  greeting: "Welcome to the catalog from the config server"
