spring:
  datasource:
    url: jdbc:mysql://localhost/fileuplaod
    username: root
    password: root123
    # postgredb:
      # jdbcurl: jdbc:postgresql://localhost/fileupload
      # username: postgres
      # password: root123
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true

# logging:
#   level:
#     org:
#       springframework:
#         web: debug

# PostGreSql
# spring:
#   datasource:
#     postgredb:
#       jdbc-url: jdbc:postgresql://localhost/fileupload
#       username: postgres
#       password: root123
#   jpa:
#     hibernate:
#       postgredb:
#         ddl-auto: update

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7070/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh

polar:
  greeting: "Welcome to the catalog from the config server"
